services:
  zerodowndeploy-blue: &app
    container_name: zerodowndeploy-blue
    image: ghcr.io/jamie-mh/zerodowndeploy:latest
    restart: always
    networks:
      - zerodowndeploy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_interval: 10s
      start_period: 30s

  zerodowndeploy-green:
    <<: *app
    container_name: zerodowndeploy-green

  zerodowndeploy-caddy:
    container_name: zerodowndeploy-caddy
    image: ghcr.io/jamie-mh/zerodowndeploy-caddy:latest
    restart: always
    ports:
      - 8083:8083
    networks:
      - zerodowndeploy

networks:
  zerodowndeploy:
    driver: bridge
